# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gkintana <gkintana@student.42abudhabi.ae>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/29 21:08:22 by gkintana          #+#    #+#              #
#    Updated: 2022/06/19 21:42:46 by gkintana         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:	
		@make -C ex00/ all
		@make -C ex01/ all
# @make -C ex02/ all

fclean:
		@make -C ex00/ fclean
		@make -C ex01/ fclean
# @make -C ex02/ fclean

re:		fclean all

.PHONY:		all fclean re
