# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gkintana <gkintana@student.42abudhabi.ae>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/29 21:08:22 by gkintana          #+#    #+#              #
#    Updated: 2022/05/29 21:18:52 by gkintana         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:	
		@make -C ex00/ all
		@make -C ex01/ all
		@make -C ex02/ all
		@make -C ex03/ all
		@make -C ex04/ all
		@make -C ex05/ all
		@make -C ex06/ all

fclean:
		@make -C ex00/ fclean
		@make -C ex01/ fclean
		@make -C ex02/ fclean
		@make -C ex03/ fclean
		@make -C ex04/ fclean
		@make -C ex05/ fclean
		@make -C ex06/ fclean

re:		fclean all

.PHONY:		all fclean re
